models:
  - name: "RAG Assistant WebUI"
    model_path: "/models"
    service:
      pre_start_actions:
        - action: run_command
          args:
            command: ["/bin/bash", "/models/auto_rag_service/setup.sh"]
      start_command:
        - /bin/bash
        - /models/auto_rag_service/start.sh
        - docs_path
      port: 8000
